### ISSUE TITLE
可以尝试使用类似UDC网站子分类标签

### ISSUE THREAD

**Issue by ciaranchen** [phcp-tech/hkc#2]
目前HKC的网站看起来比[UDC网站](http://www.udcsummary.info/php/index.php?lang=chi)的网站更加现代化，但是UDC网站有做的更好的是它的每个分类都是可以点开的，即使是父分类也是可以点击，并且获得解释的。

将`折叠/展开`功能仅做在父分类前的小标签上可以达到这种效果，然后添加父分类的页面。我相信这样内容可以更加丰富。

**Comment by CHCP** [comment]
非常感谢您的建议。我们会考虑您的建议然后更好的实现它。目前这个界面仅仅是个演示版本，后面还是需要进一步演化的。
