### ISSUE TITLE
Enhancement 增加目录下载

### ISSUE THREAD

**Issue by zcker** [phcp-tech/hkc#4]
希望能够增加知识库的中英文目录结构下载，如果手打太过麻烦了，感谢😀

**Comment by rts-gordon** [comment]
Hi @zcker 
已经增加了HKC文件夹zip包（中英文），可以下载后解压缩在Windows, Linux系统上使用。
还增加了HKC Chrome书签（中英文），可以下载后通过Chrome/Bookmarks/Bookmark manager/Import Bookmarks导入使用。
[请参考附件：](https://github.com/CHCP/hkc#3)

感谢提出的意见。

**Comment by zcker** [comment]
赞
![013DA92A](https://user-images.githubusercontent.com/45120415/163703676-49c4c65c-f14e-4e9d-a944-b47ad2661f41.png)
